### ISSUE TITLE
Local symbolization failed

### ISSUE THREAD

**Issue by zhixinwen** [polarsignals/rust-jemalloc-pprof#8]
Hello,

This is more of a question rather than a real issue. I do not understand the underlying of pprof well, and could not figure out what was going wrong.

I am coming from Golang background, and pprof works out of box for CPU and memory with [pprof package - net/http/pprof - Go Packages](https://pkg.go.dev/net/http/pprof). Nice and easy.

When I work on Rust, I find CPU profile works similarly to Go. But for memory, it is not out of box with this lib.

The way I used rust-jemalloc-pprof is:

1. setup some web handlers, so profile is triggered when receiving a request like /debug/pprofile/heap
2. curl the handler remotely from my local machine
3. use pprof to analyze the profile dump on my local machine.

I find it works for Golang cpu/heap and Rust cpu profile. But for memory, I am seeing Local symbolization failed for xxxxx-a2099af8e65d354b (build ID c04fcdbe120999b2): stat /tmp/xxxxx-a2099af8e65d354b. I can get around it by setting PPROF_BINARY_PATHand download xxxxx-a2099af8e65d354b to my local host.

But I do not understand why I only need to do this for Rust jemalloc memory profile and is there anyway for me to get it work automatically?

**Comment by brancz** [comment]
I don't know what you use for CPU profiling Rust so why it works there I can't answer, but otherwise this sounds like it works as expected. This library produces profiling data that is not symbolized, so all the profiling data is memory addresses that make up the stack. In Go the profiling data is immediately symbolized before serving it on the HTTP endpoint, this can be done reliably because the Go runtime requires the `.gopclntab` section to be present, which contains symbols required. In Rust no such assumption can be made as all debuginfo is optional. So the pprof toolchain when looking at data needs the debuginfo available to symbolize the profiling data before showing it to you.

Does that clarify things?

**Comment by zhixinwen** [comment]
Thanks for the detailed explanation! If I want the Rust profile to contain symbolize info as well, what is the recommended way to do that? Should I add some extra flags when compiling the program, or call some other APIs manually and insert the data in the profile dump, or something else?

**Comment by zhixinwen** [comment]
I end up calling `pprof` in the binary to add symbolization.

**Comment by zuston** [comment]
> I end up calling `pprof` in the binary to add symbolization.

How to do it? Can you share something?
